name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.0.1
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: any
  firebase_storage: any
  sqflite: any
  path: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
